mod baha;
mod bilibili;
mod bilisubtitle;
mod bilivideo;
mod douyu;
mod fudujikiller;
mod huya;
mod mkv_header;
mod twitch;
mod youtube;

use crate::dmlive::DMLContext;
use anyhow::Result;
use chrono::{Duration, NaiveTime};
use log::info;
use std::cell::Cell;
use std::cell::RefCell;
use std::collections::BTreeMap;
use std::ops::{BitXor, Not};
use std::path::{Path, PathBuf};
use std::rc::Rc;
use tokio::io::AsyncWriteExt;

const ASS_HEADER_TEXT: &'static str = r#"[Script Info]
; Script generated by dmlive 
; https://github.com/THMonster/Revda
Title: Danmaku file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Sans,40,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,0,7,0,0,0,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"#;
// const EMOJI_RE: &'static str = r#"[\x{1F300}-\x{1F5FF}|\x{1F1E6}-\x{1F1FF}|\x{2700}-\x{27BF}|\x{1F900}-\x{1F9FF}|\x{1F600}-\x{1F64F}|\x{1F680}-\x{1F6FF}|\x{2600}-\x{26FF}]"#;

#[derive(Clone, Debug)]
struct DanmakuChannel {
    length: usize,
    begin_pts: u64,
}

#[derive(Clone, Debug)]
pub struct DMLDanmaku {
    time: i64,
    text: String,
    nick: String,
    color: String,
    position: u8,
}

#[derive(Clone, Debug)]
pub struct SubtitleTrackFile {
    pub path: PathBuf,
    pub title: String,
    pub language: String,
    pub selected: bool,
}

struct AssDocuments {
    danmaku: Option<String>,
    subtitle: Option<String>,
    combined: Option<String>,
}

fn compose_ass_documents(header: &str, danmaku: Option<&str>, subtitle: Option<&str>) -> AssDocuments {
    AssDocuments {
        danmaku: danmaku.map(|events| format!("{header}{events}")),
        subtitle: subtitle.map(|events| format!("{header}{events}")),
        combined: danmaku.zip(subtitle).map(|(danmaku, subtitle)| format!("{header}{danmaku}{subtitle}")),
    }
}

pub struct Danmaku {
    ctx: Rc<DMLContext>,
    show_nick: Cell<bool>,
    font_size: Cell<usize>,
    channel_num: Cell<usize>,
    ratio_scale: Cell<f64>,
    read_order: Cell<usize>,
    bili_video_bvid: RefCell<String>,
    bili_video_cid: RefCell<String>,
    bili_video_generation: Cell<u64>,
    dchannels: RefCell<Vec<DanmakuChannel>>,
    fk: fudujikiller::FudujiKiller,
}

impl Danmaku {
    pub fn new(ctx: Rc<DMLContext>) -> Self {
        let font_size = (40.0 * ctx.cm.font_scale.get()) as usize;
        let ch = vec![
            DanmakuChannel {
                length: 0,
                begin_pts: 0
            };
            30
        ];
        Self {
            ctx,
            show_nick: Cell::new(false),
            font_size: Cell::new(font_size),
            channel_num: Cell::new((540.0 / font_size as f64).ceil() as usize),
            ratio_scale: Cell::new(1.0),
            read_order: Cell::new(0),
            fk: fudujikiller::FudujiKiller::new(),
            bili_video_bvid: RefCell::new("".into()),
            bili_video_cid: RefCell::new("".into()),
            bili_video_generation: Cell::new(0),
            dchannels: RefCell::new(ch),
        }
    }

    pub fn reset(&self) {
        for it in self.dchannels.borrow_mut().iter_mut() {
            it.length = 0;
            it.begin_pts = 0;
        }
        self.read_order.set(0)
    }

    pub async fn set_speed(&self, speed: u64) {
        if (1000..30000).contains(&speed) {
            self.ctx.cm.danmaku_speed.set(speed);
            let _ = self.ctx.cm.write_config().await;
        }
    }

    pub async fn set_font_size(&self, font_scale: f64) {
        if font_scale > 0.0 {
            self.font_size.set((40.0 * font_scale) as usize);
            self.channel_num.set((540.0 / self.font_size.get() as f64).ceil() as usize);
            self.ctx.cm.font_scale.set(font_scale);
            let _ = self.ctx.cm.write_config().await;
        }
    }

    pub async fn set_font_alpha(&self, font_alpha: f64) {
        if (0.0..=1.0).contains(&font_alpha) {
            self.ctx.cm.font_alpha.set(font_alpha);
            let _ = self.ctx.cm.write_config().await;
        }
    }

    pub fn set_ratio_scale(&self, ratio_scale: f64) {
        self.ratio_scale.set(ratio_scale);
    }

    pub async fn set_bili_video_cid(&self, cid: &str) {
        let mut bvc = self.bili_video_cid.borrow_mut();
        bvc.clear();
        bvc.push_str(cid);
    }

    pub fn set_bili_video_info(&self, bvid: &str, cid: &str) -> u64 {
        *self.bili_video_bvid.borrow_mut() = bvid.to_string();
        *self.bili_video_cid.borrow_mut() = cid.to_string();
        let generation = self.bili_video_generation.get().wrapping_add(1);
        self.bili_video_generation.set(generation);
        generation
    }

    pub fn bili_video_info(&self) -> Option<(u64, String, String)> {
        let bvid = self.bili_video_bvid.borrow().clone();
        let cid = self.bili_video_cid.borrow().clone();
        (!bvid.is_empty() && !cid.is_empty()).then(|| (self.bili_video_generation.get(), bvid, cid))
    }

    pub fn is_current_bili_video(&self, generation: u64, cid: &str) -> bool {
        self.bili_video_generation.get() == generation && self.bili_video_cid.borrow().as_str() == cid
    }

    pub async fn toggle_show_nick(&self) {
        self.show_nick.set(self.show_nick.get().bitxor(true));
    }

    fn get_avail_danmaku_channel(&self, c_pts: u64, len: usize) -> Option<usize> {
        let s = (1920.0 + len as f64) / self.ctx.cm.danmaku_speed.get() as f64;
        for (i, c) in self.dchannels.borrow_mut().iter_mut().enumerate() {
            if i >= self.channel_num.get() {
                break;
            }
            if c.length == 0 {
                c.length = len;
                c.begin_pts = c_pts;
                return Some(i);
            }
            if ((self.ctx.cm.danmaku_speed.get() as f64 - c_pts as f64 + c.begin_pts as f64) * s) > 1920.0 {
                continue;
            } else if ((c.length + 1920) as f64 * (c_pts as f64 - c.begin_pts as f64)
                / self.ctx.cm.danmaku_speed.get() as f64)
                < c.length as f64
            {
                continue;
            } else {
                c.length = len;
                c.begin_pts = c_pts;
                return Some(i);
            }
        }
        None
    }

    fn get_danmaku_display_length(&self, nick: &str, dm: &str) -> usize {
        let mut ascii_num = 0;
        let mut non_ascii_num = 0;
        for c in dm.chars() {
            if c.is_ascii() {
                ascii_num += 1;
            } else {
                non_ascii_num += 1;
            }
        }
        if self.show_nick.get() {
            for c in nick.chars() {
                if c.is_ascii() {
                    ascii_num += 1;
                } else {
                    non_ascii_num += 1;
                }
            }
            non_ascii_num += 1;
        }
        let fs = self.font_size.get();
        (((fs as f64 * 0.75 * non_ascii_num as f64) + (fs as f64 * 0.50 * ascii_num as f64)) * self.ratio_scale.get())
            .round() as usize
    }

    fn launch_single_danmaku(
        &self, d: &DMLDanmaku, cluster: &RefCell<mkv_header::DMKVCluster>, track_number: u8,
    ) -> Result<()> {
        let mut out_of_channel = false;
        let mut f1 = || {
            d.color.trim().is_empty().not().then(|| {})?;
            let display_length = self.get_danmaku_display_length(&d.nick, &d.text);
            self.get_avail_danmaku_channel(d.time as u64, display_length)
                .or_else(|| {
                    out_of_channel = true;
                    None
                })
                .map(|it| (it, display_length))
        };
        let (ass, du) = if d.position == 0 {
            match f1() {
                Some((avail_dc, display_length)) => {
                    let ass = format!(
                        r"{4},0,Default,{5},0,0,0,,{{\alpha{0}\fs{7}\1c&{6}&\move(1920,{1},{2},{1})}}{8}{9}{3}",
                        format_args!("{:02x}", (self.ctx.cm.font_alpha.get() * 255_f64) as u8),
                        avail_dc * self.font_size.get(),
                        0 - display_length as isize,
                        &d.text,
                        self.read_order.get(),
                        &d.nick,
                        format_args!("{}{}{}", &d.color[4..6], &d.color[2..4], &d.color[0..2]),
                        self.font_size.get(),
                        if self.show_nick.get() { &d.nick } else { "" },
                        if self.show_nick.get() { ": " } else { "" },
                    )
                    .into_bytes();
                    (ass, self.ctx.cm.danmaku_speed.get())
                    // (ass, 1000)
                }
                None => {
                    let ass = format!(r"{},0,Default,dmlive-empty,0,0,0,,", self.read_order.get()).into_bytes();
                    (ass, if track_number == 1 { 0 } else { 200 })
                }
            }
        } else {
            let ass = format!(
                r"{0},0,Default,{1},0,0,0,,{{\alpha{2}\fs{3}\1c&{4}&\an{5}}}{6}{7}{8}",
                self.read_order.get(),
                &d.nick,
                format_args!("{:02x}", (self.ctx.cm.font_alpha.get() * 255_f64) as u8),
                self.font_size.get(),
                format_args!("{}{}{}", &d.color[4..6], &d.color[2..4], &d.color[0..2]),
                d.position,
                if self.show_nick.get() { &d.nick } else { "" },
                if self.show_nick.get() { ": " } else { "" },
                &d.text,
            )
            .into_bytes();
            (ass, self.ctx.cm.danmaku_speed.get())
        };
        self.read_order.update(|x| x + 1);
        let _ = cluster.borrow_mut().add_ass_block(d.time as u64, ass, du, track_number);
        // out_of_channel.not().then(|| {}).ok_or_else(|| anyhow!("channels unavailable"))
        Ok(())
    }

    async fn launch_live_danmaku_task(&self, rx: async_channel::Receiver<DMLDanmaku>) -> Result<()> {
        let now = std::time::Instant::now();
        let padding_time = Cell::new(0);
        let mut socket = self.ctx.im.get_danmaku_socket().await?;
        let mut empty_dm = DMLDanmaku {
            text: "".to_string(),
            nick: "".to_string(),
            color: "".to_string(),
            time: 0,
            position: 0,
        };
        let mkv_cluster = RefCell::new(mkv_header::DMKVCluster::new());
        socket.write_all(mkv_header::MKV_HEADER).await?;
        let t1 = async {
            while let Ok(mut dml_dm) = rx.recv().await {
                if !self.ctx.cm.quiet {
                    println!("[{}] {}", &dml_dm.nick, &dml_dm.text);
                }
                if !self.fk.dm_check(&dml_dm.text) {
                    continue;
                }
                dml_dm.time = now.elapsed().as_millis() as i64 + padding_time.get();
                self.launch_single_danmaku(&dml_dm, &mkv_cluster, 1)?;
            }
            anyhow::Ok(())
        };

        let t2 = async {
            let mut interval = tokio::time::interval(tokio::time::Duration::from_millis(1000));
            mkv_cluster.borrow_mut().reset(0);
            for _ in 0..100 {
                empty_dm.time = padding_time.get();
                padding_time.update(|x| x + 1);
                self.launch_single_danmaku(&empty_dm, &mkv_cluster, 1)?;
                self.launch_single_danmaku(&empty_dm, &mkv_cluster, 2)?;
            }
            loop {
                interval.tick().await;
                let now_ts = now.elapsed().as_millis() as i64 + padding_time.get();
                empty_dm.time = now_ts;
                self.launch_single_danmaku(&empty_dm, &mkv_cluster, 1)?;
                self.launch_single_danmaku(&empty_dm, &mkv_cluster, 2)?;
                let data = mkv_cluster.borrow().write_to_bytes();
                mkv_cluster.borrow_mut().reset(now_ts as u64);
                socket.write_all(&data).await?;
            }
            #[allow(unreachable_code)]
            anyhow::Ok(())
        };
        tokio::select! {
            it = t1 => { it?; },
            it = t2 => { it?; },
        }
        Ok(())
    }

    async fn launch_video_danmaku_task(&self, rx: async_channel::Receiver<DMLDanmaku>) -> Result<()> {
        let mut socket = self.ctx.im.get_danmaku_socket().await?;
        let mut dm_map: BTreeMap<i64, DMLDanmaku> = BTreeMap::new();
        while let Ok(d) = rx.recv().await {
            dm_map.insert(d.time, d);
        }
        socket.write_all(ASS_HEADER_TEXT.as_bytes()).await?;
        for (k, v) in dm_map.into_iter() {
            info!("{}-{}-{}-{}", k, &v.text, v.position, &v.color);
            let t1 = NaiveTime::from_hms_opt(0, 0, 0).unwrap() + Duration::milliseconds(k);
            let t2 = t1 + Duration::milliseconds(self.ctx.cm.danmaku_speed.get() as i64);
            let mut t1_s = t1.format("%k:%M:%S%.3f").to_string();
            let mut t2_s = t2.format("%k:%M:%S%.3f").to_string();
            t1_s.remove(t1_s.len() - 1);
            t2_s.remove(t2_s.len() - 1);
            if v.position == 0 {
                let display_length = self.get_danmaku_display_length(&v.nick, &v.text);
                let avail_dc = match self.get_avail_danmaku_channel(k as u64, display_length) {
                    Some(it) => it,
                    None => {
                        continue;
                    }
                };
                let ass = format!(
                    r#"Dialogue: 0,{4},{5},Default,,0,0,0,,{{\alpha{0}\fs{7}\1c&{6}&\move(1920,{1},{2},{1})}}{3}"#,
                    format_args!("{:02x}", (self.ctx.cm.font_alpha.get() * 255_f64) as u8),
                    avail_dc * self.font_size.get(),
                    0 - display_length as isize,
                    v.text,
                    t1_s,
                    t2_s,
                    format_args!("{}{}{}", &v.color[4..6], &v.color[2..4], &v.color[0..2]),
                    self.font_size.get(),
                );
                socket.write_all(ass.as_bytes()).await?;
                socket.write_all("\n".as_bytes()).await?;
            } else {
                let ass = format!(
                    r#"Dialogue: 0,{4},{5},Default,,0,0,0,,{{\alpha{0}\fs{3}\1c&{2}&\an{6}}}{1}"#,
                    format_args!("{:02x}", (self.ctx.cm.font_alpha.get() * 255_f64) as u8),
                    v.text,
                    format_args!("{}{}{}", &v.color[4..6], &v.color[2..4], &v.color[0..2]),
                    self.font_size.get(),
                    t1_s,
                    t2_s,
                    v.position
                );
                socket.write_all(ass.as_bytes()).await?;
                socket.write_all("\n".as_bytes()).await?;
            }
        }
        Ok(())
    }

    fn ass_header(&self) -> String {
        format!(
            r#"[Script Info]
; Script generated by dmlive
; https://github.com/THMonster/Revda
Title: dmlive subtitles
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Danmaku,Sans,{0},&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,0,7,0,0,0,1
Style: Subtitle,Sans,52,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,3,0,2,60,60,45,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"#,
            self.font_size.get()
        )
    }

    fn ass_time(milliseconds: u64) -> String {
        let centiseconds = milliseconds / 10;
        let hours = centiseconds / 360_000;
        let minutes = centiseconds / 6_000 % 60;
        let seconds = centiseconds / 100 % 60;
        let fraction = centiseconds % 100;
        format!("{hours}:{minutes:02}:{seconds:02}.{fraction:02}")
    }

    fn escape_ass_text(text: &str) -> String {
        let mut escaped = String::with_capacity(text.len());
        let mut chars = text.chars().peekable();
        while let Some(ch) = chars.next() {
            match ch {
                '\r' => {
                    if chars.peek() == Some(&'\n') {
                        chars.next();
                    }
                    escaped.push_str(r"\N");
                }
                '\n' => escaped.push_str(r"\N"),
                '\\' => escaped.push('＼'),
                '{' => escaped.push('｛'),
                '}' => escaped.push('｝'),
                ch if ch.is_control() => {}
                ch => escaped.push(ch),
            }
        }
        escaped
    }

    fn render_danmaku_events(&self, mut danmaku: Vec<DMLDanmaku>) -> String {
        danmaku.sort_by_key(|item| item.time);
        let mut events = String::new();
        for item in danmaku {
            if item.time < 0 || item.text.trim().is_empty() || !self.fk.dm_check(&item.text) {
                continue;
            }
            let start = item.time as u64;
            let end = start.saturating_add(self.ctx.cm.danmaku_speed.get());
            let text = Self::escape_ass_text(&item.text);
            let color = if item.color.len() == 6 {
                format!(
                    "{}{}{}",
                    &item.color[4..6],
                    &item.color[2..4],
                    &item.color[0..2]
                )
            } else {
                "FFFFFF".to_string()
            };
            let alpha = format!("{:02x}", (self.ctx.cm.font_alpha.get() * 255_f64) as u8);
            let event = if item.position == 0 {
                let display_length = self.get_danmaku_display_length(&item.nick, &item.text);
                let Some(channel) = self.get_avail_danmaku_channel(start, display_length) else {
                    continue;
                };
                format!(
                    "Dialogue: 0,{},{},Danmaku,,0,0,0,,{{\\alpha{}\\fs{}\\1c&{}&\\move(1920,{},-{},{})}}{}\n",
                    Self::ass_time(start),
                    Self::ass_time(end),
                    alpha,
                    self.font_size.get(),
                    color,
                    channel * self.font_size.get(),
                    display_length,
                    channel * self.font_size.get(),
                    text,
                )
            } else {
                format!(
                    "Dialogue: 0,{},{},Danmaku,,0,0,0,,{{\\alpha{}\\fs{}\\1c&{}&\\an{}}}{}\n",
                    Self::ass_time(start),
                    Self::ass_time(end),
                    alpha,
                    self.font_size.get(),
                    color,
                    item.position,
                    text,
                )
            };
            events.push_str(&event);
        }
        events
    }

    fn render_subtitle_events(cues: &[bilisubtitle::SubtitleCue]) -> String {
        let mut events = String::new();
        for cue in cues {
            events.push_str(&format!(
                "Dialogue: 10,{},{},Subtitle,,0,0,0,,{}\n",
                Self::ass_time(cue.from_ms),
                Self::ass_time(cue.to_ms),
                Self::escape_ass_text(&cue.content),
            ));
        }
        events
    }

    async fn write_ass(path: &Path, content: &str) -> Result<()> {
        let temporary = path.with_extension("ass.tmp");
        tokio::fs::write(&temporary, content).await?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            tokio::fs::set_permissions(&temporary, std::fs::Permissions::from_mode(0o600)).await?;
        }
        tokio::fs::rename(temporary, path).await?;
        Ok(())
    }

    pub async fn build_bilivideo_tracks(
        &self, generation: u64, bvid: &str, cid: &str, ratio_scale: f64,
    ) -> Result<Vec<SubtitleTrackFile>> {
        info!("ratio: {}", &ratio_scale);
        self.reset();
        self.ratio_scale.set(ratio_scale);
        let cookies = if self.ctx.cm.cookies_from_browser.is_empty() {
            self.ctx.cm.bcookie.clone()
        } else {
            match crate::utils::cookies::get_cookies_from_browser(&self.ctx.cm.cookies_from_browser, ".bilibili.com")
                .await
            {
                Ok(cookies) => cookies,
                Err(error) => {
                    log::warn!("failed to read browser cookies for video subtitles: {error}");
                    self.ctx.cm.bcookie.clone()
                }
            }
        };
        let danmaku_url = format!("https://api.bilibili.com/x/v1/dm/list.so?oid={cid}");
        let bilivideo = bilivideo::Bilibili::new();
        let danmaku_request = bilivideo.fetch(&danmaku_url);
        let subtitle_request = bilisubtitle::fetch_selected(bvid, cid, &cookies);
        let (danmaku_result, subtitle_result) = tokio::join!(danmaku_request, subtitle_request);
        let danmaku = danmaku_result.map_err(|error| log::warn!("video danmaku request failed: {error}")).ok();
        let subtitle =
            subtitle_result.map_err(|error| log::warn!("video subtitle request failed: {error}")).ok().flatten();

        if !self.is_current_bili_video(generation, cid) {
            return Ok(Vec::new());
        }

        let header = self.ass_header();
        let danmaku_events = danmaku.map(|items| self.render_danmaku_events(items));
        let subtitle_events = subtitle.as_ref().map(|item| Self::render_subtitle_events(&item.cues));
        let documents = compose_ass_documents(
            &header,
            danmaku_events.as_deref(),
            subtitle_events.as_deref(),
        );
        let directory = self.ctx.im.get_subtitle_dir();
        tokio::fs::create_dir_all(&directory).await?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            tokio::fs::set_permissions(
                self.ctx.im.get_process_temp_dir(),
                std::fs::Permissions::from_mode(0o700),
            )
            .await?;
            tokio::fs::set_permissions(&directory, std::fs::Permissions::from_mode(0o700)).await?;
        }
        let prefix = format!("{generation}-{cid}");
        let mut tracks = Vec::new();
        if let Some(document) = &documents.danmaku {
            let path = directory.join(format!("{prefix}-danmaku.ass"));
            match Self::write_ass(&path, document).await {
                Ok(()) => tracks.push(SubtitleTrackFile {
                    path,
                    title: "弹幕".into(),
                    language: "und".into(),
                    selected: false,
                }),
                Err(error) => log::warn!("failed to write danmaku ASS track: {error}"),
            }
        }
        if let (Some(subtitle), Some(document)) = (&subtitle, &documents.subtitle) {
            let label = format!(
                "{}{}",
                subtitle.title,
                if subtitle.is_ai { "（AI）" } else { "" }
            );
            if let Some(document) = &documents.combined {
                let path = directory.join(format!("{prefix}-combined.ass"));
                match Self::write_ass(&path, document).await {
                    Ok(()) => tracks.push(SubtitleTrackFile {
                        path,
                        title: format!("弹幕 + 字幕 · {label}"),
                        language: subtitle.language.clone(),
                        selected: false,
                    }),
                    Err(error) => log::warn!("failed to write combined ASS track: {error}"),
                }
            }
            let path = directory.join(format!("{prefix}-subtitle.ass"));
            match Self::write_ass(&path, document).await {
                Ok(()) => tracks.push(SubtitleTrackFile {
                    path,
                    title: format!("字幕 · {label}"),
                    language: subtitle.language.clone(),
                    selected: false,
                }),
                Err(error) => log::warn!("failed to write subtitle ASS track: {error}"),
            }
        }
        if let Some(track) = tracks.first_mut() {
            track.selected = true;
        }
        Ok(tracks)
    }

    pub async fn danmaku_client_task(&self, dtx: async_channel::Sender<DMLDanmaku>) -> Result<()> {
        loop {
            match match self.ctx.cm.site {
                crate::config::Site::BiliLive => {
                    let b = bilibili::Bilibili::new();
                    b.run(&self.ctx.cm.room_url, dtx.clone()).await
                }
                crate::config::Site::BiliVideo => {
                    let b = bilivideo::Bilibili::new();
                    b.run(
                        format!(
                            "http://api.bilibili.com/x/v1/dm/list.so?oid={}",
                            self.bili_video_cid.borrow()
                        )
                        .as_str(),
                        dtx.clone(),
                    )
                    .await
                }
                crate::config::Site::BahaVideo => {
                    let b = baha::Baha::new();
                    b.run(self.bili_video_cid.borrow().to_string(), dtx.clone()).await
                }
                crate::config::Site::DouyuLive => {
                    let b = douyu::Douyu::new();
                    b.run(&self.ctx.cm.room_url, dtx.clone()).await
                }
                crate::config::Site::HuyaLive => {
                    let b = huya::Huya::new();
                    b.run(&self.ctx.cm.room_url, dtx.clone()).await
                }
                crate::config::Site::TwitchLive => {
                    let b = twitch::Twitch::new();
                    b.run(&self.ctx.cm.room_url, dtx.clone()).await
                }
                crate::config::Site::YoutubeLive => {
                    let b = youtube::Youtube::new();
                    b.run(&self.ctx.cm.room_url, dtx.clone()).await
                }
            } {
                Ok(_) => {}
                Err(e) => {
                    info!("danmaku client error: {:?}", e);
                }
            };
            if dtx.is_closed() {
                break;
            }
            tokio::time::sleep(tokio::time::Duration::from_secs(1)).await;
        }
        info!("danmaku client exited.");
        Ok(())
    }

    pub async fn run_baha(&self) -> Result<()> {
        self.reset();
        let (dtx, drx) = async_channel::unbounded();
        let (dc_res, fbd_res) = tokio::join!(
            self.danmaku_client_task(dtx),
            self.launch_video_danmaku_task(drx)
        );
        dc_res?;
        fbd_res?;
        info!("baha danmaku exited");
        Ok(())
    }

    pub async fn run_bilivideo(&self, ratio_scale: f64) -> Result<()> {
        info!("ratio: {}", &ratio_scale);
        self.reset();
        self.ratio_scale.set(ratio_scale);
        let (dtx, drx) = async_channel::unbounded();
        let (dc_res, fbd_res) = tokio::join!(
            self.danmaku_client_task(dtx),
            self.launch_video_danmaku_task(drx)
        );
        dc_res?;
        fbd_res?;
        info!("bilibili video danmaku exited");
        Ok(())
    }

    pub async fn run(&self) -> Result<()> {
        self.reset();
        let (dtx, drx) = async_channel::unbounded();
        tokio::select! {
            it = self.danmaku_client_task(dtx) => { it?; },
            it = self.launch_live_danmaku_task(drx) => { it?; },
        }
        info!("danmaku exited");
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ass_time_supports_fractional_seconds_and_long_videos() {
        assert_eq!(Danmaku::ass_time(0), "0:00:00.00");
        assert_eq!(Danmaku::ass_time(1_234), "0:00:01.23");
        assert_eq!(Danmaku::ass_time(3_661_999), "1:01:01.99");
    }

    #[test]
    fn ass_text_is_safe_and_preserves_line_breaks() {
        assert_eq!(
            Danmaku::escape_ass_text("a\\{b}\r\nc\n😀\u{0001}"),
            "a＼｛b｝\\Nc\\N😀"
        );
    }

    #[test]
    fn ass_documents_keep_tracks_separate() {
        let documents = compose_ass_documents("HEADER\n", Some("DANMAKU\n"), Some("SUBTITLE\n"));
        assert_eq!(documents.danmaku.as_deref(), Some("HEADER\nDANMAKU\n"));
        assert_eq!(documents.subtitle.as_deref(), Some("HEADER\nSUBTITLE\n"));
        assert_eq!(
            documents.combined.as_deref(),
            Some("HEADER\nDANMAKU\nSUBTITLE\n")
        );

        let documents = compose_ass_documents("HEADER\n", Some("DANMAKU\n"), None);
        assert!(documents.subtitle.is_none());
        assert!(documents.combined.is_none());
    }
}
